# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/terminal_llm',
                'doc_host': 'https://ForBo7.github.io',
                'git_url': 'https://github.com/ForBo7/terminal_llm',
                'lib_path': 'terminal_llm'},
  'syms': {'terminal_llm.chat': {}}}
