# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_chat.ipynb.

# %% auto 0
__all__ = ['Chat']

# %% ../nbs/00_chat.ipynb 14
from mistralai.client import MistralClient
from mistralai.models.chat_completion import ChatMessage

# %% ../nbs/00_chat.ipynb 48
class Chat:
  def __init__(self, api_key, model):
    '''Initialize the class.'''
    self.client = MistralClient(api_key=api_key)
    self.model = model
    self.history = []


  def __call__(self, query): 
    '''Send a query to the model and return the response.'''
    messages = self.history + [ChatMessage(role='user', content=query)]
    response = self.client.chat(model=self.model, messages=messages).choices[0].message.content
    self.write_history(query, response)
    return response
  
  
  def write_history(self, query, response):
    '''Store the query and response in the history.'''
    self.history.append(ChatMessage(role='user', content=query))
    self.history.append(ChatMessage(role='assistant', content=response))
