# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_interface.ipynb.

# %% auto 0
__all__ = ['UserInterface']

# %% ../nbs/01_interface.ipynb 3
from fastcore.all import *
from .chat import Chat

# %% ../nbs/01_interface.ipynb 7
class UserInterface:
    def __init__(self): pass
    
    def start_app(self):
      # TODO: Perhaps shift to constructor?
      # TODO: Encrypt files.
      print('Starting app...')
      if Path('.storage').exists():
        try:
          with open('.storage/api_key.txt', 'r') as f: api_key = f.read
        except FileNotFoundError: 
          # TODO: Add a check to see whether entered API key is valid.
          api_key = input('API key not found. Enter API Key: ')
          with open('.storage/api_key.txt', 'w') as f: f.write(api_key)
          print('API key saved.')
        try:
          with open('.storage/model.txt', 'r') as f: model = f.read
        except FileNotFoundError: 
          # TODO: Add a check to see whether entered model exists.
          model = input('Model not found. Enter Model: ')
          with open('.storage/model.txt', 'w') as f: f.write(model)
          print('Model saved.')
      else:
        Path('.storage').mkdir()
        api_key = input('Enter API Key: ')
        with open('.storage/api_key.txt', 'w') as f: f.write(api_key)
        print('API key saved.')
        model = input('Enter Model: ')
        with open('.storage/model.txt', 'w') as f: f.write(model)
        print('Model saved.')
      print('No errors found. Starting menu...')
      

    def menu(self):
      print("Welcome to the chat interface. Type 'quit' to exit.")
      print("0 – Settings")
      print("1 – Start Chat")
      print("2 – Previous Chats")
      print("3 – Exit")

      while True:
        choice = input('... ')
        if   choice == '0': self.settings()
        elif choice == '1': self.start_chat()
        elif choice == '2': self.previous_chats()
        elif choice == '3': break
        else              : print('Invalid choice.')
                
        # TODO: Implement full processing on exit term.
        # if user_input.lower() == 'quit': break
        # response = self.chat(user_input)
        # print(f"Assistant: {response}")

    def settings(self):
      print("Settings")
      print("0 – Change API Key")
      print("1 – Change Model")
      print("2 – Back")
      choice = input('... ')
      
      if   choice == '0':
        api_key = input('Enter API Key: ')
        # TODO: Add a check to see whether entered API key is valid.
        with open('.storage/api_key.txt', 'w') as f: f.write(api_key)
        print('API key saved.')
      elif choice == '1':
        # TODO: Add a check to see whether entered model exists.
        model = input('Enter Model: ')
        with open('.storage/model.txt', 'w') as f: f.write(model)
        print('Model saved.')
      elif choice == '2': pass
      else							: print('Invalid choice.')
      
    
    def start_chat(self):
        # TODO: Hook up .storage files to Chat class.
        print("Start Chat")
        with open('.storage/api_key.txt', 'r') as f: api_key = f.read()
        with open('.storage/model.txt', 'r') as f: model = f.read()
        self.chat = Chat(api_key, model)
        while True:
          user_input = input('You: ')
          if user_input.lower() == 'quit': break
          response = self.chat(user_input)
          print(f"Assistant: {response}")
    
    def previous_chats(self):
        print("Previous Chats")
        pass

