# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_run.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/03_run.ipynb 3
#| eval: false
if __name__ == "__main__": from terminal_llm.interface import Interface; Interface().menu()
