# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_session_handler.ipynb.

# %% auto 0
__all__ = ['SessionHandler']

# %% ../nbs/02_session_handler.ipynb 3
from fastcore.all import *
class SessionHandler():
  def __init__(self): pass
  
  def start_app(self):
    print('Starting app...')
    # TODO: Implement loading animation.
    if Path('.storage').exists():
      try:
        self.api_key = self.read_file('.storage/api_key.txt')
      except FileNotFoundError: 
        # TODO: Add a check to see whether entered API key is valid.
        self.api_key = input('API key not found. Enter API Key: ')
        self.write_file('.storage/api_key.txt', self.api_key)
        print('API key saved.')
      
      try:
        self.model = self.read_file('.storage/model.txt')
      except FileNotFoundError: 
        # TODO: Add a check to see whether entered model exists.
        self.model = input('Model not found. Enter Model: ')
        self.write_file('.storage/model.txt', self.model)
        print('Model saved.')
    else:
      Path('.storage').mkdir()
      self.api_key = input('Enter API Key: ')
      self.write_file('.storage/api_key.txt', self.api_key)
      print('API key saved.')

      self.model = input('Enter Model: ')
      self.write_file('.storage/model.txt', self.model)
      print('Model saved.')

    print('No errors found. Starting menu...')

  def read_file(self, f_path):
    with open(f_path, 'r') as f: return f.read()
  
  def write_file(self, f_path, content):
    with open(f_path, 'w') as f: f.write(content)
  
  
